import { chromium, devices } from 'playwright'
const BASE='http://localhost:4175/orders/?local=1'
function ok(c,m){ if(!c){ console.error('  ✗',m); process.exitCode=1; throw new Error(m) } console.log('  ✓',m) }
const b=await chromium.launch(); const p=await (await b.newContext({...devices['Pixel 5']})).newPage()
p.on('pageerror',e=>{ console.error('  PAGEERR',e.message); process.exitCode=1 })
try{
  await p.goto(BASE,{waitUntil:'networkidle'}); await p.evaluate(()=>localStorage.clear()); await p.reload({waitUntil:'networkidle'})
  console.log('\n[1] Role chooser'); await p.waitForSelector('text=Production Manager')
  ok(await p.locator('text=Owner').first().isVisible(),'Manager + Owner offered')
  console.log('\n[2] Manager login + new order')
  await p.locator('button:has-text("Production Manager")').click()
  await p.fill('input[type=password]','nsp@123'); await p.click('text=Unlock')
  await p.waitForSelector('text=New Order')
  ok((await p.locator('text=Dashboard').count())===0,'Manager does NOT see Dashboard (ownerOnly hidden)')
  await p.locator('text=New Order').first().click()
  await p.waitForSelector('text=Client')
  ok((await p.locator('text=Price').count())===0,'Manager does NOT see Price field')
  await p.fill('input[placeholder="Client name"]','Acme Corp')
  await p.locator('select').first().selectOption({label:'Spider'})
  await p.fill('input[placeholder="qty"]','100')
  await p.click('button:has-text("Save Order")')
  await p.waitForSelector('text=/Order UO-0001 saved/')
  ok(true,'Order UO-0001 saved by manager')
  console.log('\n[3] Order Book shows it')
  await p.click('text=Home'); await p.locator('text=Order Book').first().click()
  await p.waitForSelector('text=Acme Corp')
  ok(true,'Order Book lists Acme Corp')
  console.log('\n[4] Owner sees money + dashboard')
  await p.locator('button:has-text("Switch")').click()
  await p.locator('button:has-text("Owner")').click()
  await p.fill('input[type=password]','6133923_N'); await p.click('text=Unlock')
  await p.waitForSelector('text=Dashboard')
  ok((await p.locator('text=Dashboard').count())>0,'Owner sees Dashboard card')
  await p.locator('text=Dashboard').first().click()
  await p.waitForSelector('text=Order Value')
  ok(await p.locator('text=Order Value').first().isVisible(),'Owner dashboard shows money')
  console.log('\n✅ ORDERS CHECKS PASSED')
}catch(e){ console.error('FAIL',e.message); await p.screenshot({path:'ofail.png'}).catch(()=>{}); process.exitCode=1 }
finally{ await b.close() }
